### ISSUE TITLE
New build configuration

### ISSUE THREAD

**Issue by qgu** [percival-detector/cppprocessing#4]
I have done the following changes to build configurations. Require some changes to cmake and travis.
1. included tbb library.
2. included a new build configuration parallel_profile and parallel_debug, which exclude profile/main.cpp and include parallel_test/main.cpp. Otherwise the configurations are the same as Debug and Profile configurations.

**Comment by ulrikpedersen** [comment]
That's great. I'm already working on the cmake/travis tweaks...

**Comment by ulrikpedersen** [comment]
OK, I have added TBB configurations to the cmake build system and Travis-CI. The new pcvl-tbb application is now automatically built and run if TBB is present on the system.

Here is the first fully working travis build/run: https://travis-ci.org/percival-detector/cppprocessing/builds/76125339

Closing ticket.
